stages:
  - build
  - release

variables:
  EXE_NAME: "BolderPlus.exe"

build_executable:
  stage: build
  tags:
    - saas-windows-medium-amd64
  rules:
    - if: '$CI_COMMIT_TAG =~ /-RELEASE$/'
  script:
    - choco install python --yes
    - py -m pip install pyinstaller
    - py -m PyInstaller --onefile main.py --no-console --hidden-import=google
  artifacts:
    paths:
      - dist/main.exe

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /-RELEASE$/'
  script:
    - VERSION_NAME=$(echo "$CI_COMMIT_TAG" | sed 's/-RELEASE$//') # Extract version number
    - echo "Creating GitLab release for version $VERSION_NAME"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$VERSION_NAME"
    description: "Release for $CI_COMMIT_TAG"
    assets:
      links:
        - name: "$EXE_NAME"
          filepath: "$CI_PROJECT_DIR/$EXE_NAME"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/$EXE_NAME"
